steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']
- name: "gcr.io/cloud-builders/docker"
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - run
  - --filename=gke.yml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=europe-central2-a
  - --cluster=gcp-devops-project-gke-cluster
  - --namespace=gcp-devops-prod